package com.soapsoft.Model;
// Generated 27/11/2017 08:22:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbOrdenCompra generated by hbm2java
 */
@Entity
@Table(name="tb_orden_compra"
    ,catalog="soap_soft"
)
public class TbOrdenCompra  implements java.io.Serializable {


     private int id;
     private TbProveedor tbProveedor;
     private int creadorPor;
     private Date creadoEn;
     private String modificadoPor;
     private Date modificadoEn;
     private String observacion;
     private Set tbDetalleOrdenCompras = new HashSet(0);

    public TbOrdenCompra() {
    }

	
    public TbOrdenCompra(int id, TbProveedor tbProveedor, int creadorPor, Date creadoEn) {
        this.id = id;
        this.tbProveedor = tbProveedor;
        this.creadorPor = creadorPor;
        this.creadoEn = creadoEn;
    }
    public TbOrdenCompra(int id, TbProveedor tbProveedor, int creadorPor, Date creadoEn, String modificadoPor, Date modificadoEn, String observacion, Set tbDetalleOrdenCompras) {
       this.id = id;
       this.tbProveedor = tbProveedor;
       this.creadorPor = creadorPor;
       this.creadoEn = creadoEn;
       this.modificadoPor = modificadoPor;
       this.modificadoEn = modificadoEn;
       this.observacion = observacion;
       this.tbDetalleOrdenCompras = tbDetalleOrdenCompras;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_proveedor", nullable=false)
    public TbProveedor getTbProveedor() {
        return this.tbProveedor;
    }
    
    public void setTbProveedor(TbProveedor tbProveedor) {
        this.tbProveedor = tbProveedor;
    }

    
    @Column(name="creadorPor", nullable=false)
    public int getCreadorPor() {
        return this.creadorPor;
    }
    
    public void setCreadorPor(int creadorPor) {
        this.creadorPor = creadorPor;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="creadoEn", nullable=false, length=19)
    public Date getCreadoEn() {
        return this.creadoEn;
    }
    
    public void setCreadoEn(Date creadoEn) {
        this.creadoEn = creadoEn;
    }

    
    @Column(name="modificadoPor", length=50)
    public String getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(String modificadoPor) {
        this.modificadoPor = modificadoPor;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modificadoEn", length=19)
    public Date getModificadoEn() {
        return this.modificadoEn;
    }
    
    public void setModificadoEn(Date modificadoEn) {
        this.modificadoEn = modificadoEn;
    }

    
    @Column(name="observacion", length=200)
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbOrdenCompra")
    public Set getTbDetalleOrdenCompras() {
        return this.tbDetalleOrdenCompras;
    }
    
    public void setTbDetalleOrdenCompras(Set tbDetalleOrdenCompras) {
        this.tbDetalleOrdenCompras = tbDetalleOrdenCompras;
    }




}


