package com.soapsoft.Model;
// Generated 27/11/2017 08:22:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbProduccion generated by hbm2java
 */
@Entity
@Table(name="tb_produccion"
    ,catalog="soap_soft"
)
public class TbProduccion  implements java.io.Serializable {


     private Integer id;
     private String idDptoProduccion;
     private String creadoPor;
     private Date creadoEn;
     private String observacion;
     private String modificadoPor;
     private Date modificadoEn;

    public TbProduccion() {
    }

	
    public TbProduccion(String idDptoProduccion, String creadoPor, Date creadoEn, String observacion) {
        this.idDptoProduccion = idDptoProduccion;
        this.creadoPor = creadoPor;
        this.creadoEn = creadoEn;
        this.observacion = observacion;
    }
    public TbProduccion(String idDptoProduccion, String creadoPor, Date creadoEn, String observacion, String modificadoPor, Date modificadoEn) {
       this.idDptoProduccion = idDptoProduccion;
       this.creadoPor = creadoPor;
       this.creadoEn = creadoEn;
       this.observacion = observacion;
       this.modificadoPor = modificadoPor;
       this.modificadoEn = modificadoEn;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="id_dpto_produccion", nullable=false, length=100)
    public String getIdDptoProduccion() {
        return this.idDptoProduccion;
    }
    
    public void setIdDptoProduccion(String idDptoProduccion) {
        this.idDptoProduccion = idDptoProduccion;
    }

    
    @Column(name="creadoPor", nullable=false, length=50)
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="creadoEn", nullable=false, length=19)
    public Date getCreadoEn() {
        return this.creadoEn;
    }
    
    public void setCreadoEn(Date creadoEn) {
        this.creadoEn = creadoEn;
    }

    
    @Column(name="observacion", nullable=false, length=200)
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    
    @Column(name="modificadoPor", length=50)
    public String getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(String modificadoPor) {
        this.modificadoPor = modificadoPor;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modificadoEn", length=19)
    public Date getModificadoEn() {
        return this.modificadoEn;
    }
    
    public void setModificadoEn(Date modificadoEn) {
        this.modificadoEn = modificadoEn;
    }




}


