package com.soapsoft.Model;
// Generated 27/11/2017 08:22:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbSalidaMateriaPrima generated by hbm2java
 */
@Entity
@Table(name="tb_salida_materia_prima"
    ,catalog="soap_soft"
)
public class TbSalidaMateriaPrima  implements java.io.Serializable {


     private Integer id;
     private TbProductoTerminado tbProductoTerminado;
     private String dptoProducion;
     private String creadoPor;
     private Date creadoEn;
     private String modificadoPor;
     private Date modificadoEn;
     private Set tbDetalleSalidaMateriaPrimas = new HashSet(0);

    public TbSalidaMateriaPrima() {
    }

	
    public TbSalidaMateriaPrima(TbProductoTerminado tbProductoTerminado, String dptoProducion, String creadoPor, Date creadoEn) {
        this.tbProductoTerminado = tbProductoTerminado;
        this.dptoProducion = dptoProducion;
        this.creadoPor = creadoPor;
        this.creadoEn = creadoEn;
    }
    public TbSalidaMateriaPrima(TbProductoTerminado tbProductoTerminado, String dptoProducion, String creadoPor, Date creadoEn, String modificadoPor, Date modificadoEn, Set tbDetalleSalidaMateriaPrimas) {
       this.tbProductoTerminado = tbProductoTerminado;
       this.dptoProducion = dptoProducion;
       this.creadoPor = creadoPor;
       this.creadoEn = creadoEn;
       this.modificadoPor = modificadoPor;
       this.modificadoEn = modificadoEn;
       this.tbDetalleSalidaMateriaPrimas = tbDetalleSalidaMateriaPrimas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_producto_terminado", nullable=false)
    public TbProductoTerminado getTbProductoTerminado() {
        return this.tbProductoTerminado;
    }
    
    public void setTbProductoTerminado(TbProductoTerminado tbProductoTerminado) {
        this.tbProductoTerminado = tbProductoTerminado;
    }

    
    @Column(name="dpto_producion", nullable=false, length=100)
    public String getDptoProducion() {
        return this.dptoProducion;
    }
    
    public void setDptoProducion(String dptoProducion) {
        this.dptoProducion = dptoProducion;
    }

    
    @Column(name="creadoPor", nullable=false, length=50)
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="creadoEn", nullable=false, length=19)
    public Date getCreadoEn() {
        return this.creadoEn;
    }
    
    public void setCreadoEn(Date creadoEn) {
        this.creadoEn = creadoEn;
    }

    
    @Column(name="modificadoPor", length=50)
    public String getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(String modificadoPor) {
        this.modificadoPor = modificadoPor;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modificadoEn", length=19)
    public Date getModificadoEn() {
        return this.modificadoEn;
    }
    
    public void setModificadoEn(Date modificadoEn) {
        this.modificadoEn = modificadoEn;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbSalidaMateriaPrima")
    public Set getTbDetalleSalidaMateriaPrimas() {
        return this.tbDetalleSalidaMateriaPrimas;
    }
    
    public void setTbDetalleSalidaMateriaPrimas(Set tbDetalleSalidaMateriaPrimas) {
        this.tbDetalleSalidaMateriaPrimas = tbDetalleSalidaMateriaPrimas;
    }




}


